### PR TITLE
fixes failed dirty check for non-english git

### PR DESCRIPTION
**Pull request by cybernetlab**
Hi! For non-english locales `git status` command responds with text that doesn't inclulde `nothing to commit` string. As a result repo seems as dirty for your task. `git` manpage (`man git status`) points me to `--porcelain` option that gives output for scripts and if there are nothing to commit it gives an empty string.

Example of `git status` output for russian locale:

```
$ git status
В ветке master
Your branch is up-to-date with 'origin/master'.

нечего фиксировать, рабочая директория пуста
```

Regards!

### CODE REVIEW

**Comment by rmm5t** [comment]
Thanks for this submission. Looks good. 

I'm working on getting my collaborator access reinstated on this project (it moved owners at some point), but in the meantime, if you can fix this branch to avoid the version bump, that would be helpful. It will make it easier to pull in once I get the commit bit back. As an aside, it's usually best never to bump a version as part of a pull-request unless the pull-request is specifically about versioning.

**Comment by cybernetlab** [comment]
Ok - I'll just remove changes in `version.rb` file. Is it right now?

**Comment by rmm5t** [comment]
@cybernetlab Yes, that'll do. Squashing the two commits into one would be better, but that'll require an interactive rebase and force push on your end. Depending on your level of comfort with git, don't sweat it.

**Comment by rmm5t** [comment]
Loving it. Thanks! :beers:

**Comment by cybernetlab** [comment]
;)

**Pull request merged**
